### ISSUE TITLE
不兼容

### ISSUE THREAD

**Issue by nlh1996** [SaekiRaku/vscode-rainbow-fart#1]
![image](https://user-images.githubusercontent.com/33018375/83470103-f71a0400-a4b3-11ea-948e-00ba4accbcba.png)

**Comment by nlh1996** [comment]
无法安装扩展名'saekiraku.rainbow-fart'，因为它不兼容 VS Code '1.33.1'。

**Comment by SaekiRaku** [comment]
我降低了 VSCode 的版本要求配置，并重新推送了一版，请重新下载安装。

I have lower the required version of VSCode, and publish a new release. Please download and try to install again.

---

通常情况下，我建议你升级 VSCode 以匹配插件。因为 VSCode API 文档没有提供某个 API 增添的日期和版本。因此我无法确定哪些版本的 VSCode 是否可以运行这个插件，所以我直接使用了我自己当前的 VSCode 版本号。

Normally, I recommend to upgrade your VSCode to compatible with this extension. Because VSCode API document didn't provide the version or date when some API was added. So I can't be certain which version of VSCode can or can not run this extension, I simply use my current VSCode version as defaults.

为了避免以后类似的问题，我在此处留下修改可运行版本的流程：

In order to avoid similar problems in the future, I write down the process of modifying the runnable version here:

修改 package.json 中的 `engines.vscode` 和 `devDependencies.@types/vscode` 字段为你当前的版本号，然后运行 `npm I && npm run build`。

Modify the `engines.vscode` and `devDependencies.@types/vscode` property of `package.json` to your current VSCode version, and then run `npm I && npm run build`.

```json
{
  "engines": {
      "vscode": "^[当前版本号/Current VSCode Version]",
  },
  "devDependencies": {
      "@types/vscode": "^[当前版本号/Current VSCode Version]",
  }
}
```

有时候，进行上述操作后插件依然无法正确运行，此时则表示你确实需要升级 VSCode 了。

Sometimes, after performing the above operations, the extension still does not run correctly, which means that you really need to upgrade VSCode.
