### ISSUE TITLE
请问考虑出 WebStorm版本的插件吗

### ISSUE THREAD

**Issue by ljybill** [SaekiRaku/vscode-rainbow-fart#3]
如题；插件很有意思！

**Comment by SaekiRaku** [comment]
我没有用过 WebStorm，不太熟悉它们开放的 API 。不过，如果可行的话会考虑移植，但是会需要一段时间。所以，近期我会优先将核心部分独立出来以方便移植。如果有熟悉 WebStorm 和任何其他编辑器或IDE的开发者，欢迎提交 PR。

---

I haven't used the WebStorm and I'm not familiar with its API. However, I'm willing to transplant if it is available, but it will take a while. So, I'm going to make the core independent to make it easier to transplant, so that if anyone familiar with the API of WebStorm, welcome to push PR.

**Comment by ljybill** [comment]
赞，加油。 忙完工作上的事情拜读下代码

**Comment by SaekiRaku** [comment]
Closed due to we already have the plugin for WebStorm version, you can find it here: https://github.com/izhangzhihao/intellij-rainbow-fart

Thanks for all the outstanding contributions from the open-source community!
