### ISSUE TITLE
command `rainbow-fart.enable` not found

### ISSUE THREAD

**Issue by wuzuoliang** [SaekiRaku/vscode-rainbow-fart#42]
i have install this plugins.

**Comment by SaekiRaku** [comment]
Thanks for your feedback.

Did you install the extension by the VSCode marketplace? If so and still get this error, please run `> Help: About` by VSCode command panel and copy the information of your VSCode version and system for me.

**Comment by UltramanWeiLai** [comment]
I have this problem 
版本: 1.36.1
Electron: 4.2.5
chrome: 69.0.3497.128
node.js 10.11.0
v8 : 6.9.427.31-electron.0
OS: windows_NT x64 10.0.17763

**Comment by SaekiRaku** [comment]
@wuzuoliang @UltramanWeiLai 

I may have located the problem, but for now, I recommend you to upgrade your VSCode (I'm using 1.46.1) , it's the fast way to solve most of the starting problem.

Because all the version of VSCode below 1.40 were published a year ago, it's a very long time. The API of the VSCode had changed a lot, and it will cause errors when the extension called a new API that doesn't exist in the earlier version, then everything will be stuck. I can fix this issue, but it will take a while to figure out which API has changed.

**Comment by SaekiRaku** [comment]
Closed due to no more reply, feel free to reopen this issue if you have any updates.
